name: CI

on:
  push:       # FOR TESTING
    branches: # FOR TESTING
      - initial-idea  # FOR TESTING
  release:
    types:
      - published

jobs:
  python:
    name: Python
    uses: ./.github/workflows/docker-build-deploy.yml
    with:
      image-name: tna-python
      dockerfile: docker/tna-python/Dockerfile

  python-django:
    name: Python Django
    needs: python
    uses: ./.github/workflows/docker-build-deploy.yml
    with:
      image-name: tna-python-django
      dockerfile: docker/tna-python-django/Dockerfile